JournalNOEP_UI/Controllers/ConferenceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using JournalNOEP_DOMAIN;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VURO.UI.Models;

namespace VURO.ADMIN.Controllers
{
    public class ConferenceController : Controller
    {
        private readonly IRepository _repository;
        IHostingEnvironment _appEnvironment;
        public ConferenceController(IHostingEnvironment appEnvironment, IRepository repository, IHostingEnvironment environment)
        {
            _appEnvironment = appEnvironment;
            _repository = repository;
        }
        #region [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Редактирование года]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
        public IActionResult Index(Guid? idedition)
        {
            ViewBag.idedition = idedition ?? null;
            DataConferenceViewModel dataViewModel = new DataConferenceViewModel()
            {
                DataConferenceYearList = _repository.DataConferenceYears.Include(x=>x.DataConferenceEditions).OrderByDescending(x => x.Year)
            };
            return View(dataViewModel);
        }
        public IActionResult PartialEditYear(Guid? Id)
        {
            Guid id = Id ?? Guid.Empty;
            DataConferenceYear dataYear = _repository.DataConferenceYears.FirstOrDefault(x => x.Id == id);
            return View(dataYear);
        }
        public void EditYear(DataConferenceYear dataYear)
        {
            if (dataYear.Id == Guid.Empty)
            {
                dataYear.Id = Guid.NewGuid();
                _repository.Insert(dataYear);
                DataConferenceEdition dataEdition = new DataConferenceEdition()
                {
                    Id = Guid.NewGuid(),
                    DataConferenceYearId = dataYear.Id,
                    
                };
                _repository.Insert(dataEdition);
            }
            else
            {
                _repository.Update(dataYear);
            }
            RedirectToAction("Index");
        }

        public IActionResult PartialRemoveYear(Guid Id)
        {
            DataConferenceYear dataYear = _repository.DataConferenceYears.FirstOrDefault(x => x.Id == Id);
            return View(dataYear);
        }

        [HttpPost]
        public IActionResult RemoveYear(DataConferenceYear dataYear)
        {
            DeleteYear(dataYear);
            return RedirectToAction("Index");
        }
        #endregion

        #region [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Редактирование выпуска]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
        public IActionResult PartialEditEdition(Guid? IdYear, Guid? IdEdition)
        {
            Guid idyear = IdYear ?? Guid.Empty;
            Guid idedition = IdEdition ?? Guid.Empty;
            DataConferenceEdition model;
            if (idyear != Guid.Empty)
            {
                var i = _repository.DataConferenceEditions.Where(x => x.DataConferenceYearId == idyear).Max(x => x.Edition);
                model = new DataConferenceEdition()
                {
                    DataConferenceYearId = idyear,
                    Edition = i + 1
                };
            }
            else
            {
                model = _repository.DataConferenceEditions.FirstOrDefault(x => x.Id == idedition);
            }

            return View(model);
        }
        [HttpPost]

        public IActionResult EditEdition(DataConferenceEdition dataEdition)
        {
            if (dataEdition.Id == Guid.Empty)
            {
                dataEdition.Id = Guid.NewGuid();
                _repository.Insert(dataEdition);
                return RedirectToAction("Index");
            }
            else
            {
                _repository.Update(dataEdition);
                return RedirectToAction("Index", new { idedition = dataEdition.Id });
            }
        }
        public IActionResult PartialRemoveEdition(Guid IdEdition)
        {

            var model = _repository.DataConferenceEditions.FirstOrDefault(x => x.Id == IdEdition);

            return View(model);
        }
        [HttpPost]
        public IActionResult RemoveEdition(DataConferenceEdition dataEdition)
        {
            DeleteEdition(dataEdition);
            return RedirectToAction("Index");
        }
        public IActionResult PartialEditEditionFile(Guid Id)
        {
            var model = _repository.DataEdition.FirstOrDefault(x => x.Id == Id);
            return PartialView("Edition/PartialEditEditionFile", model);
        }
        public async Task<IActionResult> EditEditionFile(DataEdition dedition, IFormFile EditionFileNew)
        {
            var _edition = _repository.DataConferenceEditions.Include(z => z.DataConferenceYear).FirstOrDefault(x => x.Id == dedition.Id);
            // путь к папке Files
            string fileName = _edition.DataConferenceYear.Year + "_" + _edition.Edition + Path.GetExtension(EditionFileNew.FileName);
            string path = Path.Combine("/Files", "EditionFiles", fileName);
            using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
            {
                await EditionFileNew.CopyToAsync(fileStream);
            }
            _edition.EdFile = fileName;
            _repository.Update(_edition);
            return RedirectToAction("Index", new { idedition = _edition.Id });
        }
        public IActionResult PartialRemoveEditionFile(Guid Id)
        {
            var model = _repository.DataConferenceEditions.FirstOrDefault(x => x.Id == Id);
            return PartialView("Edition/PartialRemoveEditionFile", model);
        }
        public IActionResult RemoveEditionFile(DataEdition dedition)
        {
            var _edition = _repository.DataConferenceEditions.FirstOrDefault(x => x.Id == dedition.Id);
            _edition.EdFile = null;
            _repository.Update(_edition);
            return RedirectToAction("Index", new { idedition = dedition.Id });
        }

        #endregion

        #region [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Редактирование статьи]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
        public IActionResult Edition(Guid? idedition)
        {

            var model = _repository.DataConferenceArticles.Include(z => z.DataConferenceEdition).ThenInclude(c => c.DataConferenceYear).Where(x => x.DataConferenceEditionId == idedition).Include(a => a.DataConferenceArticleAuthors).ThenInclude(b => b.SprJoiurnalAuthors).OrderBy(x => x.ArtPos).ToList();
            var edition = _repository.DataConferenceEditions.Include(w => w.DataConferenceYear).FirstOrDefault(x => x.Id == idedition);

            ViewBag.EditionNumber = edition.Edition;
            ViewBag.IdEdition = idedition;
            ViewBag.EditionYear = edition.DataConferenceYear.Year;
            ViewBag.EditionFile = edition.EdFile;


            return PartialView("Edition/Index", model);
        }
        public IActionResult PartialEditArticleFile(Guid Id)
        {
            var model = _repository.DataConferenceArticles.FirstOrDefault(x => x.Id == Id);
            return PartialView("Edition/PartialEditArticleFile", model);
        }
        [HttpPost]
        public async Task<IActionResult> EditArticleFile(Articles articless, IFormFile ArtFileNew)
        {

            var articles = _repository.DataConferenceArticles.FirstOrDefault(x => x.Id == articless.Id);
            // путь к папке Files
            string fileName = Guid.NewGuid() + Path.GetExtension(ArtFileNew.FileName);
            string path = Path.Combine("/Files", "ArticleFiles", fileName);
            using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
            {
                await ArtFileNew.CopyToAsync(fileStream);
            }
            articles.ArtFile = fileName;
            _repository.Update(articles);
            return RedirectToAction("Index", new { idedition = articles.DataConferenceEditionId });
        }
        public IActionResult PartialEditArticle(Guid? Id, Guid IdEdition)
        {
            Guid id = Id ?? Guid.Empty;
            var model = _repository.DataConferenceArticles.Include(z => z.DataConferenceArticleAuthors).ThenInclude(w => w.SprJoiurnalAuthors).FirstOrDefault(x => x.Id == id);
            List<SprJoiurnalAuthors> allAuth = _repository.SprJoiurnalAuthors.OrderBy(x => x.AuthFio).ToList();
            if (model != null)
            {
                List<DataConferenceArticleAuthor> artAuthList = model.DataConferenceArticleAuthors.ToList();
                List<SprJoiurnalAuthors> artAuth = new List<SprJoiurnalAuthors>();
                foreach (var item in artAuthList)
                {
                    SprJoiurnalAuthors auth = _repository.SprJoiurnalAuthors.FirstOrDefault(x => x.Id == item.SprJoiurnalAuthorsId);
                    allAuth.Remove(auth);
                    artAuth.Add(auth);
                }
                ViewBag.AuthorsInArticle = artAuth;
            }
            ViewBag.AuthorsOutArticles = allAuth;
            //ViewBag.Sections = _repository.SprJournalSection.OrderBy(x => x.SectionName);
            ViewBag.IdEdition = IdEdition;
            return PartialView("Edition/PartialEditArticle", model);
        }
        [HttpPost]
        public async Task<IActionResult> EditArticle(DataConferenceArticle articles, IFormFile ArtFileNew, Guid[] ArtAuthors)
        {
            if (ArtFileNew != null)
            {
                // путь к папке Files
                string fileName = Guid.NewGuid() + Path.GetExtension(ArtFileNew.FileName);
                string path = Path.Combine("/Files", "ArticleFiles", fileName);
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))

JournalNOEP_UI/Views/Conference/Edition/Index.cshtml
@model IEnumerable<JournalNOEP_DOMAIN.DataConferenceArticle>


<div id="modDialogArticle" class="modal fade p-0"></div>
@{ int i = 0; }
<div class="card border-secondary mg-t-100">
    <div class="card-header bg-primary tx-white" style="margin-top:-100px">
        <div class="row align-baseline">
            <div class="col-md-9 pt-2">
                Конференция №@ViewBag.EditionNumber, @ViewBag.EditionYear г.

                <a href="#" data-idedition="@ViewBag.IdEdition" data-toggle="modal" data-target="#dialogContent" data-edit-edition>
                    <i class="fa fa-edit p-2 text-secondary"></i>
                </a>

                <a href="#" data-idedition="@ViewBag.IdEdition" data-toggle="modal" data-target="#dialogContent" data-remove-edition>
                    <i class="fa fa-remove text-danger p-2"></i>
                </a>

            </div>
            
            <div class="col-md-3 text-right">
                <a href="#" class="btn btn-outline-secondary" data-toggle="modal" data-target="#dialogContent" data-idedition="@ViewBag.IdEdition" data-edit-article>
                    <i class="fa fa-plus mg-r-10"></i>
                    Добавить
                </a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="table-wrapper">
            <div class="row mg-t-20  btn input-group p-0" style="margin-bottom:-15px;">
                <div class="col-md-12 input-group p-2 pd-b-0 align-baseline">
                    <i class="fa fa-2x fa-file-pdf-o pd-b-0"></i>
                    <h3 class=" pd-b-0">PDF</h3>
                    @{if (ViewBag.EditionFile == null)
                        {
                            <a href="#" data-idedition="@ViewBag.IdEdition" class="btn-outline-primary btn-icon btn-sm p-0 mg-l-5" data-toggle="modal" data-target="#dialogContent" data-edit-edition-file>
                                <div>
                                    <i class="fa fa-plus"></i>
                                </div>
                            </a>
                        }
                        else
                        {
                            <a href="#" data-idedition="@ViewBag.IdEdition" class="btn-outline-warning btn-icon btn-sm p-0 mg-l-5" data-toggle="modal" data-target="#dialogContent" data-show-edition-file>
                                <div>
                                    <i class="fa fa-window-restore"></i>
                                </div>
                            </a>
                            <a href="#" data-idedition="@ViewBag.IdEdition" class="btn-outline-primary btn-icon btn-sm p-0 mg-l-5" data-toggle="modal" data-target="#dialogContent" data-edit-edition-file>
                                <div>
                                    <i class="fa fa-edit"></i>
                                </div>
                            </a>
                            <a href="#" data-idedition="@ViewBag.IdEdition" class="btn-outline-danger btn-icon btn-sm p-0 mg-l-5" data-toggle="modal" data-target="#dialogContent" data-remove-edition-file>
                                <div>
                                    <i class="fa fa-remove"></i>
                                </div>
                            </a>
                        }
                    }
                </div>
                </div>
            <hr />
                <table id="datatable1" class="table display responsive mg-t-10">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>УДК</th>
                            <th>Название</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="gradeX">
                                <td>
                                    @(i = i + 1)
                                </td>
                                <td>
                                    <b>
                                        UDK:@item.ArtUdk
                                    </b>
                                </td>
                                <td>
                                    @item.ArtName
                                    <br /> 
                                    <ion-icon name="person"></ion-icon>
                                    @foreach (var author in @item.DataConferenceArticleAuthors.OrderBy(x=>x.AuthorPos))
                                    {
                                        <i style="font-size:12px;">@author.SprJoiurnalAuthors.AuthFio; </i>
                                    }
                                </td>
                                <td style="width:157px">
                                    <a href="#" class="btn btn-outline-primary btn-icon mg-r-5" data-idarticle="@item.Id" data-edit-article-file>
                                        <div>
                                            <i class="icon ion-document-text"></i>
                                        </div>
                                    </a>
                                    <a href="#" class="btn btn-outline-primary btn-icon mg-r-5" data-idarticle="@item.Id" data-idedition="@item.DataConferenceEditionId" data-edit-article>
                                        <div>
                                            <i class="icon ion-edit"></i>
                                        </div>
                                    </a>
                                    <a href="#" class="btn btn-outline-danger btn-icon mg-r-5" data-remove-article data-idarticle="@item.Id">
                                        <div>
                                            <i class="icon ion-trash-a"></i>
                                        </div>
                                    </a>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
    </div>
</div>
<script>

    $('[data-edit-edition]').click(function () {
        $.ajax({
            method: "POST",
             url: "@Url.Action("PartialEditEdition", "Conference")",
            data: { IdEdition: $(this).data('idedition') },

            success: function (content) {
                $('#modDialogArticle').html(content);
                $('#modDialogArticle').modal('show');
            }
        });
    });
    $('[data-remove-edition]').click(function () {
        $.ajax({
            method: "POST",
             url: "@Url.Action("PartialRemoveEdition", "Conference")",
            data: { IdEdition: $(this).data('idedition') },

            success: function (content) {
                $('#modDialogArticle').html(content);
                $('#modDialogArticle').modal('show');
            }
        });
    });
    $('[data-edit-article]').click(function () {
        $.ajax({
            method: "POST",
            url: "@Url.Action("PartialEditArticle", "Conference")",
            data: { Id: $(this).data('idarticle'), IdEdition: $(this).data('idedition') },
            success: function (content) {
                $('#modDialogArticle').html(content);
                $('#modDialogArticle').modal('show');
            }
        });
    });
    $('[ data-edit-article-file]').click(function () {
        $.ajax({
            method: "POST",
             url: "@Url.Action("PartialEditArticleFile", "Conference")",
            data: { Id: $(this).data('idarticle') },

            success: function (content) {
                $('#modDialogArticle').html(content);
                $('#modDialogArticle').modal('show');
            }
        });
    });
    $('[ data-edit-edition-file]').click(function () {
        $.ajax({
            method: "POST",
             url: "@Url.Action("PartialEditEditionFile", "Conference")",
            data: { Id: $(this).data('idedition') },

            success: function (content) {
                $('#modDialogArticle').html(content);
                $('#modDialogArticle').modal('show');
            }
        });
    });
    $('[data-show-edition-file]').click(function () {
        $.ajax({
            method: "POST",
             url: "@Url.Action("PartialShowFiles", "Conference")",
            data: { id: $(this).data('idedition') },

            success: function (content) {
                $('#modDialogArticle').html(content);
                $('#modDialogArticle').modal('show');
            }
        });
    });
    $('[data-remove-edition-file]').click(function () {
        $.ajax({
            method: "POST",
             url: "@Url.Action("PartialRemoveEditionFile", "Conference")",
            data: { id: $(this).data('idedition') },

            success: function (content) {
                $('#modDialogArticle').html(content);
                $('#modDialogArticle').modal('show');
            }
        });
    });
            $('[data-remove-article]').click(function (e) {
            $.ajax({
                method: "POST",
                url: "@Url.Action("PartialRemoveArticle", "Conference")",
                data: { Id : $(this).data('idarticle') },
            success: function (content) {
                $('#modDialog').html(content);
                $('#modDialog').modal('show');
            }
        });
    });

</script>

JournalNOEP_UI/Views/Conference/Edition/PartialEditArticle.cshtml
@model JournalNOEP_DOMAIN.DataConferenceArticle


<div class="modal-dialog  modal-lg" role="document" style="min-width:800px;">
    <div class="modal-content bd-0 tx-14">
        <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Статья</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="add_edition_modal" enctype="multipart/form-data" asp-action="EditArticle" asp-controller="Conference" method="post">
                <input type="hidden" name="Id" asp-for="Id" />
                <input type="hidden" asp-for="DataConferenceEditionId" value="@ViewBag.IdEdition" />
                <input type="hidden" name="ArtFile" asp-for="ArtFile" />
                <input type="hidden" name="ArtPos" asp-for="ArtPos" />

                <div class="form-group row">
                    <div class="col-lg-6 col-md-6 col-sm-6 mg-t-20 bg-gray-300">
                        <input class="form-control" type="text" name="ArtName" id="ArtName" placeholder="Название" style="width:100%" asp-for="ArtName" required />
                        <textarea class="form-control mg-t-20" name="ArtAnnotation" placeholder="Аннотация" rows="10" style="width:100%" asp-for="ArtAnnotation" required></textarea>
                        <input class="form-control mg-t-20" type="text" name="ArtKeywords" id="ArtKeywords" placeholder="Ключевые слова" style="width:100%" asp-for="ArtKeywords" required />
                    </div>

                    <div class="col-lg-6 col-md-6 col-sm-6 mg-t-20 bg-gray-300">
                        <input class="form-control" type="text" name="ArtNameEng" placeholder="Название на английском" style="width:100%" asp-for="ArtNameEng" />
                        <textarea class="form-control mg-t-20" name="ArtAnnotationEng" placeholder="Аннотация на английском" rows="10" style="width:100%" asp-for="ArtAnnotationEng"></textarea>
                        <input class="form-control mg-t-20" type="text" name="ArtKeywordsEng" id="ArtKeywordsEng" placeholder="Keywords" style="width:100%" asp-for="ArtKeywordsEng"  />
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 mg-t-20">
                        <input class="form-control" type="text" name="ArtUdk" id="ArtUdk" placeholder="УДК" style="width:100%" asp-for="ArtUdk" required />
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 mg-t-20">
                        @if (Model == null)
                        {
                            <div class="custom-file">
                                <input type="file" class="form-control-file" name="ArtFileNew" accept="application/pdf" required>
                            </div>
                        }
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-lg-12 col-md-12 col-sm-12">

                        <select id="ArtAuthors" name="ArtAuthors" class="form-control select2" data-placeholder="Авторы статьи" style="width:100%;" multiple>
                            @if (ViewBag.AuthorsInArticle != null)
                            {
                                @foreach (var items in ViewBag.AuthorsInArticle)
                                {
                                    <option value="@items.Id" selected>@items.AuthFio</option>
                                }
                            }
                            @foreach (var items in ViewBag.AuthorsOutArticles)
                            {
                                <option value="@items.Id">@items.AuthFio</option>
                            }
                        </select>



                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="submit" form="add_edition_modal" class="btn btn-success pd-x-20">Сохранить</button>
            <button type="button" class="btn btn-secondary pd-x-20" data-dismiss="modal">Закрыть</button>
        </div>
    </div>
</div>
<script src="~/lib/select2/js/select2.js"></script>
<script src="~/lib/spectrum/spectrum.js"></script>

<script>
    $(document).ready(function () {



        $(".select2").select2({
            tags: true
        });



    });
    $(".select2").on("select2:select", function (evt) {
          var element = evt.params.data.element;
          var $element = $(element);

          if ($(this).find(":selected").length > 1) {
            var $second = $(this).find(":selected").eq(-1);
            $second.after($element);
          } else {
            $element.detach();
            $(this).prepend($element);
          }

          $(this).trigger("change");
        });

</script>

JournalNOEP_UI/Views/Conference/Edition/PartialEditArticleFile.cshtml
@model JournalNOEP_DOMAIN.DataConferenceArticle

<div class="modal-dialog modal-dialog-vertical-center" role="document">
    <div class="modal-content bd-0 tx-14">
        <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold"><i class="fa fa-file-pdf-o text-danger"></i> PDF версия конференции </h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body pd-25">
            <div class="form-group has-success mg-b-0">
                <form id="add_author_modal" asp-action="EditArticleFile" asp-controller="Conference" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="Id" asp-for="Id" />
                    <input type="hidden" name="EditionId" asp-for="DataConferenceEditionId" />

                    <input type="file" class="form-control-file" name="ArtFileNew" accept="application/pdf" required>

                </form>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" form="add_author_modal" class="btn btn-success pd-x-20">Сохранить</button>
            <button type="button" class="btn btn-secondary pd-x-20" data-dismiss="modal">Закрыть</button>
        </div>
    </div>
</div>

JournalNOEP_UI/Views/Conference/Edition/PartialEditEditionFile.cshtml
@model JournalNOEP_DOMAIN.DataConferenceEdition

<div class="modal-dialog modal-dialog-vertical-center" role="document">
    <div class="modal-content bd-0 tx-14">
        <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold"><i class="fa fa-file-pdf-o text-danger"></i> PDF версия выпуска </h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body pd-25">
            <div class="form-group has-success mg-b-0">
                <form id="add_author_modal" asp-action="EditEditionFile" asp-controller="Conference" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="Id" asp-for="Id" />

                    <input type="file" class="form-control-file" name="EditionFileNew" accept="application/pdf" required>

                </form>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" form="add_author_modal" class="btn btn-success pd-x-20">Сохранить</button>
            <button type="button" class="btn btn-secondary pd-x-20" data-dismiss="modal">Закрыть</button>
        </div>
    </div>
</div>

JournalNOEP_UI/Views/Conference/Edition/PartialRemoveArticle.cshtml
@model JournalNOEP_DOMAIN.DataConferenceArticle

<div class="modal-dialog modal-dialog-vertical-center" role="document">
    <div class="modal-content bd-0 tx-14">
        <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold">Удалить статью?</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body pd-25">
            <div class="form-group has-success mg-b-0">
                <form id="add_author_modal" asp-action="RemoveArticle" asp-controller="Conference" method="post">
                    <input type="hidden" name="Id" asp-for="Id" />
                    <input type="hidden" name="EditionId" asp-for="DataConferenceEditionId" />

                    <h3> @Model.ArtName </h3>

                </form>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" form="add_author_modal" class="btn btn-danger pd-x-20">Удалить</button>
            <button type="button" class="btn btn-secondary pd-x-20" data-dismiss="modal">Закрыть</button>
        </div>
    </div>
</div>

JournalNOEP_UI/Views/Conference/Edition/PartialRemoveEditionFile.cshtml
@model JournalNOEP_DOMAIN.DataConferenceEdition

<div class="modal-dialog modal-dialog-vertical-center" role="document">
    <div class="modal-content bd-0 tx-14">
        <div class="modal-header pd-y-20 pd-x-25">
            <h6 class="tx-14 mg-b-0 tx-uppercase tx-inverse tx-bold"><i class="fa fa-file-pdf-o text-danger"></i> </h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body pd-25">
            <div class="form-group has-success mg-b-0">
                <form id="add_author_modal" asp-action="RemoveEditionFile" asp-controller="Conference" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="Id" asp-for="Id" />
                    Удалить файл @Model.EdFile?
                </form>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" form="add_author_modal" class="btn btn-danger pd-x-20">Удалить</button>
            <button type="button" class="btn btn-secondary pd-x-20" data-dismiss="modal">Отмена</button>
        </div>
    </div>
</div>

JournalNOEP_UI/Views/Conference/Edition/PartialShowFiles.cshtml
<div class="modal-dialog modal-lg" role="document" style="width:800px;">
    <div class="modal-content bd-0 tx-14">
        <div class="modal-header pd-y-20 pd-x-25">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div id="PedigreesSireRacingModal" class="modal-body racing pd-25">
          <iframe id="iframepdf" width="750" height="650" src="@ViewBag.Path"></iframe>
        </div>

        <div class="modal-footer">
            <button type="submit" form="add_author_modal" class="btn btn-success pd-x-20">Сохранить</button>
            <button type="button" class="btn btn-secondary pd-x-20" data-dismiss="modal">Закрыть</button>
        </div>
    </div>
</div>