VURO.UI/Controllers/AuthorsController.cs
using JournalNOEP_DOMAIN;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VURO.UI.Models;

namespace VURO.UI.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IRepository _repository;


        public AuthorsController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            @ViewData["Title"] = "Поиск статей";
            MainViewModel authViewModel = new MainViewModel()
            {
                ArticleList = _repository.Articles
                .Include(x => x.DataArticleAuthors).ThenInclude(x => x.Author)
                .Include(x => x.Edition).ThenInclude(x => x.IdYearNavigation).ToList(),
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum)
            };
            return View(authViewModel);


        }
        public IActionResult Articles(Guid authId)
        {
            MainViewModel model = new MainViewModel()
            {
                DataArticleAuthorsList =  _repository.DataArticleAuthors.Where(x=>x.AuthorId == authId).Include(x=>x.Author).Include(x=>x.Article).ThenInclude(x=>x.Edition).ThenInclude(x=>x.IdYearNavigation).Include(x=>x.Article).ThenInclude(x=>x.DataArticleAuthors).ThenInclude(x=>x.Author),
                SprJoiurnalAuthor = _repository.SprJoiurnalAuthors.FirstOrDefault(x=>x.Id == authId)
            };
            return PartialView("Authors/Index", model);


        }
        
    }
}

VURO.UI/Controllers/ConferencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JournalNOEP_DOMAIN;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VURO.UI.Models;

namespace GIS.UI.Controllers
{
    public class ConferencesController : Controller
    {
        private readonly IRepository _repository;


        public ConferencesController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index(Guid? idedition)
        {
            @ViewData["Title"] = "Сборник конференций";
            ViewBag.idedition = idedition ?? null;
            MainViewModel dataViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum),
                DataConferenceYear = _repository.DataConferenceYears.Include(x=>x.DataConferenceEditions).OrderByDescending(x => x.Year)
            };
            return View(dataViewModel);
        }
        public IActionResult Articles(Guid? idedition)
        {
            var model = _repository.DataConferenceArticles.Where(x => x.DataConferenceEditionId == idedition).Include(x => x.DataConferenceArticleAuthors).ThenInclude(x => x.SprJoiurnalAuthors).OrderBy(x => x.ArtPos);
            var edition = _repository.DataConferenceEditions.Include(w => w.DataConferenceYear).FirstOrDefault(x => x.Id == idedition);
            ViewBag.EditionNumber = edition.Edition;

            ViewBag.EditionYear = edition.DataConferenceYear.Year;
            ViewBag.EditionFile = edition.EdFile;
            return PartialView("Edition/Index", model);
        }
        public IActionResult LastArticles()
        {
            try
            {
                int LastYear = _repository.DataConferenceYears.Max(x => x.Year);

                var LastEdition = _repository.DataConferenceEditions.FirstOrDefault(x => x.DataConferenceYearId == _repository.DataConferenceYears.FirstOrDefault(z => z.Year == LastYear).Id);
                var model = _repository.DataConferenceArticles.Where(x => x.DataConferenceEditionId == LastEdition.Id).Include(x => x.DataConferenceArticleAuthors).ThenInclude(x => x.SprJoiurnalAuthors).OrderBy(x => x.ArtPos);
                var edition = _repository.DataConferenceEditions.Include(w => w.DataConferenceYear).FirstOrDefault(x => x.Id == LastEdition.Id);

                ViewBag.EditionNumber = edition.Edition;

                ViewBag.EditionYear = edition.DataConferenceYear.Year;
                ViewBag.EditionFile = edition.EdFile;


                return PartialView("Edition/Index", model);
            }
            catch
            {
                return PartialView("Edition/Index");
            }
        }
        public IActionResult PartialAnnotationView(Guid? articleId)
        {

            MainViewModel articleViewModel = new MainViewModel()
            {
                DataConferenceArticle = _repository.DataConferenceArticles.FirstOrDefault(x => x.Id == articleId),
                DataConferenceArticleAuthor = _repository.DataConferenceArticleAuthors.Where(x => x.DataConferenceArticleId == articleId).Include(x => x.SprJoiurnalAuthors)
            };


            return PartialView("Edition/PartialArticleAnnotation", articleViewModel);
        }
        
        public IActionResult NewConferences()
        {
            MainViewModel dataViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum),
                DataInfo = _repository.DataInfo.FirstOrDefault(x => x.InfoNameEn.ToUpper().Contains("CONFERENCE"))
            };
            return PartialView("Edition/PartialNewConference", dataViewModel);
        }
        
        public IActionResult ApplicationConference()
        {
            MainViewModel dataViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum),
                DataInfo = _repository.DataInfo.FirstOrDefault(x => x.InfoNameEn.ToUpper().Contains("PAYMENT"))
            };
            return PartialView("Edition/PartialPayment", dataViewModel);
        }
    }
}

VURO.UI/Controllers/EditionsController.cs
using JournalNOEP_DOMAIN;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VURO.UI.Models;

namespace VURO.UI.Controllers
{
    public class EditionsController : Controller
    {
        private readonly IRepository _repository;


        public EditionsController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index(Guid? idedition)
        {
            @ViewData["Title"] = "Архив";
            ViewBag.idedition = idedition ?? null;
            MainViewModel dataViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum),
                DataYearList = _repository.DataYear.Include(x=>x.DataEdition).OrderByDescending(x => x.Year)
            };
            return View(dataViewModel);
        }
        public IActionResult Articles(Guid? idedition)
        {
            var model = _repository.Articles.Where(x => x.EditionId == idedition).Include(xx=>xx.Section).Include(x=>x.DataArticleAuthors).ThenInclude(x=>x.Author).OrderBy(x=>x.ArtPos);
            var edition = _repository.DataEdition.Include(w => w.IdYearNavigation).FirstOrDefault(x => x.Id == idedition);
            ViewBag.EditionNumber = edition.Edition;

            ViewBag.EditionYear = edition.IdYearNavigation.Year;
            ViewBag.EditionFile = edition.EdFile;
            return PartialView("Edition/Index", model);
        }
        public IActionResult LastArticles()
        {
            try
            {
                int LastYear = _repository.DataYear.Max(x => x.Year);

                var LastEdition = _repository.DataEdition.FirstOrDefault(x => x.IdYear == _repository.DataYear.FirstOrDefault(z => z.Year == LastYear).Id);
                var model = _repository.Articles.Where(x => x.EditionId == LastEdition.Id).Include(xx => xx.Section).Include(x => x.DataArticleAuthors).ThenInclude(x => x.Author).OrderBy(x => x.ArtPos);
                var edition = _repository.DataEdition.Include(w => w.IdYearNavigation).FirstOrDefault(x => x.Id == LastEdition.Id);

                ViewBag.EditionNumber = edition.Edition;

                ViewBag.EditionYear = edition.IdYearNavigation.Year;
                ViewBag.EditionFile = edition.EdFile;


                return PartialView("Edition/Index", model);
            }
            catch
            {
                return PartialView("Edition/Index");
            }
        }
        public IActionResult PartialAnnotationView(Guid? articleId)
        {

            MainViewModel articleViewModel = new MainViewModel()
            {
                Article = _repository.Articles.FirstOrDefault(x => x.Id == articleId),
                DataArticleAuthorsList = _repository.DataArticleAuthors.Where(x => x.ArticleId == articleId).Include(x => x.Author)
        };


            return PartialView("Edition/PartialArticleAnnotation", articleViewModel);
        }
    }
}

VURO.UI/Controllers/MetaDataController.cs
using JournalNOEP_DOMAIN;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VURO.UI.Models;

namespace VURO.UI.Controllers
{
    public class MetaDataController : Controller
    {
        private readonly IRepository _repository;


        public MetaDataController(IRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index(Guid? idedition)
        {
            @ViewData["Title"] = "Метаданные";
            ViewBag.idedition = idedition ?? null;
            MainViewModel dataViewModel = new MainViewModel()
            {
                DataInfoList = _repository.DataInfo.OrderBy(x => x.InfoPageNum),
                DataYearList = _repository.DataYear.Include(x=>x.DataEdition).OrderByDescending(x => x.Year)
            };
            return View(dataViewModel);
        }
        public IActionResult Articles(Guid? idedition)
        {

            var edition = _repository.DataEdition.Include(w => w.IdYearNavigation).FirstOrDefault(x => x.Id == idedition);


            var Article = _repository.Articles.Include(x => x.DataArticleAuthors).ThenInclude(c => c.Author).Where(x => x.EditionId == idedition);





            ViewBag.EditionNumber = edition.Edition;

            ViewBag.EditionYear = edition.IdYearNavigation.Year;
            ViewBag.EditionFile = edition.EdFile;
            return PartialView("Edition/Index", Article);
        }
        public IActionResult LastArticles()
        {
           

            int LastYear = _repository.DataYear.Max(x => x.Year);

            var LastEdition = _repository.DataEdition.FirstOrDefault(x => x.IdYear == _repository.DataYear.FirstOrDefault(z => z.Year == LastYear).Id);




            var Article = _repository.Articles.Include(x => x.DataArticleAuthors).ThenInclude(c => c.Author).Where(x => x.EditionId == LastEdition.Id);




            var edition = _repository.DataEdition.Include(w => w.IdYearNavigation).FirstOrDefault(x => x.Id == LastEdition.Id);

            ViewBag.EditionNumber = edition.Edition;

            ViewBag.EditionYear = edition.IdYearNavigation.Year;
            ViewBag.EditionFile = edition.EdFile;


            return PartialView("Edition/Index", Article);
            throw new Exception();
        }
    }
}

VURO.UI/Views/Shared/AllNavMenu.cshtml
@model MainViewModel
<!-- Mobile Menu -->
<nav id="menu">
    <ul>
        @if (MainViewModel.Language != "EN")
        {
            <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
            <li><a asp-action="Index" asp-controller="Editions">Журнал</a></li>
            <li><a asp-action="Index" asp-controller="Authors">Поиск статей</a></li>
            <li><a asp-action="Index" asp-controller="MetaData">Метаданные</a></li>
        }
        else
        {
            <li class="active"><a asp-action="Index" asp-controller="Home">Main</a></li>
            <li><a asp-action="Index" asp-controller="Editions">Magazine</a></li>
            <li><a asp-action="Index" asp-controller="Authors">Search for articles</a></li>
            <li><a asp-action="Index" asp-controller="MetaData">Metadata</a></li>
        }
        <li>
            <a href="#">Информация журнала</a>
            <ul>
                @foreach (var item in Model.DataInfoList)
                {
                    if (item.IsSectionOnMainPage == false)
                    {
                        @if (MainViewModel.Language != "EN")
                        {
                            <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameRu</a></li>
                        }
                        else
                        {
                            <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameEn</a></li>
                        }
                    }
                }
            </ul>
        </li>
    </ul>
</nav>

<header id="header-home-2" class="header-home bg-transparent fixed" style="background-color:#333131;">
    <h1 class="logo">
        <a href="/home/index">
            <img src="~/images/logo-on-dark.png" class="img-responsive" alt="Image">
        </a>
    </h1>
    @if (MainViewModel.Language != "EN")
    {
        <a asp-action="MyAction" asp-controller="Home" asp-route-Lang="EN" asp-route-returnUrl="@string.Format("{0}{1}",Context.Request.Path, Context.Request.QueryString)" class="ot-btn border-theme btn-contact" style="margin-top:25px;padding: 0 20px; margin-left:3px; color:gray;">EN</a>
    }
    else
    {
        <a asp-action="MyAction" asp-controller="Home" asp-route-Lang="RU" asp-route-returnUrl="@string.Format("{0}{1}",Context.Request.Path, Context.Request.QueryString)" class="ot-btn border-theme btn-contact" style="margin-top:25px;padding: 0 20px; margin-left:3px; color:gray;">RU</a>
    }

    <nav id="main-nav" class="main-nav">
        <ul>
            @if (MainViewModel.Language != "EN")
            {
                <li><a asp-action="Index" asp-controller="Editions">Журнал</a></li>
                <li><a asp-action="Index" asp-controller="Authors">Поиск статей</a></li>
                <li><a asp-action="Index" asp-controller="MetaData">Метаданные</a></li>
            }
            else
            {
                <li><a asp-action="Index" asp-controller="Editions">Magazine</a></li>
                <li><a asp-action="Index" asp-controller="Authors">Search for articles</a></li>
                <li><a asp-action="Index" asp-controller="MetaData">Metadata</a></li>
            }
            <li>
                <a href="#">Информация журнала</a>
                <ul>
                    @foreach (var item in Model.DataInfoList)
                    {
                        if (item.IsSectionOnMainPage == false)
                        {
                            @if (MainViewModel.Language != "EN")
                            {
                                <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameRu</a></li>
                            }
                            else
                            {
                                <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameEn</a></li>
                            }
                        }
                    }
                </ul>
            </li>
        </ul>
    </nav>
    <a href="#menu" class="btn-menu-mobile"><span class="lnr lnr-menu"></span></a>
</header>
<!-- /End Header 1 Warp -->

VURO.UI/Views/Shared/NavMenu.cshtml
@model MainViewModel
<!-- Mobile Menu -->


<nav class="navbar-collapse collapse" style="background-color: ghostwhite;">
    <ul class="nav navbar-nav navbar-left">
        @if (MainViewModel.Language != "EN")
        {

            <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
            <li><a asp-action="Index" asp-controller="Editions">Журнал</a></li>
            <li><a asp-action="Index" asp-controller="Authors">Поиск статей</a></li>
            <li><a asp-action="Index" asp-controller="MetaData">Метаданные</a></li>
        }
        else
        {

            <li><a asp-action="Index" asp-controller="Home">Main</a></li>
            <li><a asp-action="Index" asp-controller="Editions">Magazine</a></li>
            <li><a asp-action="Index" asp-controller="Authors">Search for articles</a></li>
            <li><a asp-action="Index" asp-controller="MetaData">Metadata</a></li>
        }
        @foreach (var item in Model.DataInfoList.Where(x => x.InfoPageNum >= 20 && x.InfoPageNum < 30))
        {
            if (item.IsSectionOnMainPage == false)
            {
                @if (MainViewModel.Language != "EN")
                {
                    <li class="menu-active"><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameRu</a></li>
                }
                else
                {
                    <li class="menu-active"><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameEn</a></li>
                }
            }
        }
        <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@(MainViewModel.Language != "EN" ? "Конференции" : "Conference")</a>
            <ul class="dropdown-menu">
                @if (MainViewModel.Language != "EN")
                {
                    <li><a asp-action="NewConferences" asp-controller="Conferences">Новые конференции</a></li>
                    <li><a asp-action="Index" asp-controller="Conferences">Сборники конференций</a></li>
                    <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="46d0bf14-515e-467f-9d03-c2560f447468">Организационный комитет</a></li>
                    <li><a asp-action="ApplicationConference" asp-controller="Conferences">Заявка и оплата</a></li>
                }
                else
                {

                    <li><a asp-action="NewConferences" asp-controller="Conferences">New conferences</a></li>
                    <li><a asp-action="Index" asp-controller="Conferences">Conference proceedings</a></li>
                    <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="46d0bf14-515e-467f-9d03-c2560f447468">Organising Committee</a></li>
                    <li><a asp-action="ApplicationConference" asp-controller="Conferences">Application and payment</a></li>
                }
            </ul>
        </li>
        <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@(MainViewModel.Language != "EN" ? "Информация журнала" : "Journal Information")</a>
            <ul class="dropdown-menu">
                @foreach (var item in Model.DataInfoList.Where(x => x.InfoPageNum < 20))
                {
                    if (item.IsSectionOnMainPage == false)
                    {
                        @if (MainViewModel.Language != "EN")
                        {
                            <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameRu</a></li>
                        }
                        else
                        {
                            <li><a asp-action="Journal" asp-controller="Home" asp-route-infoId="@item.Id">@item.InfoNameEn</a></li>
                        }
                    }
                }
            </ul>
        </li>
        @if (MainViewModel.Language != "EN")
        {
            <li><a href="https://jomeam.ru/" target="_blank">Журнал ВАК</a></li>
            <li><a href="https://voenvestnik.ru/" target="_blank">Журнал РИНЦ</a></li>
        }
        else
        {
            <li><a href="https://jomeam.ru/" target="_blank">Journal of HAC</a></li>
            <li><a href="https://voenvestnik.ru/" target="_blank">RSCI Journal</a></li>
        }
    </ul>
    <div style="width:20%; float:right;">
        <ul class="nav navbar-nav navbar-left">
            <li style="color: #337ab7; font-size:18px; margin-top:10px">ISSN: 2713-0169</li>
        </ul>
    </div>
</nav>

<!-- /End Header 1 Warp -->

VURO.UI/Views/Shared/_AllLayout.cshtml
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Вестник научной мысли</title>
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <!-- Fonts -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&subset=devanagari,latin-ext" rel="stylesheet">  -->
    <link rel="stylesheet" href="~/fonts/linearicon/style.css">
    <link rel="stylesheet" href="~/fonts/font-awesome/css/font-awesome.min.css">
    <!-- Mobile Menu -->
    <link type="text/css" rel="stylesheet" href="~/css/jquery.mmenu.all.css" />
    <!-- OWL CAROUSEL
        ================================================== -->
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />

    <!-- REVOLUTION STYLE SHEETS -->
    <link rel="stylesheet" type="text/css" href="~/revolution/css/settings.css">
    <!-- REVOLUTION LAYERS STYLES -->
    <link rel="stylesheet" type="text/css" href="~/revolution/css/layers.css">
    <!-- REVOLUTION NAVIGATION STYLES -->
    <link rel="stylesheet" type="text/css" href="~/revolution/css/navigation.css">
    <!-- Main Style -->
    <link rel="stylesheet" href="~/style.css">


    <!-- Favicons
        ================================================== -->
    <link rel="shortcut icon" href="~/images/favicon.png">
    <link href="~/revolution/css/layers.css" rel="stylesheet" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
</head>
<body class="royal_loader">
    <div id="page" style="margin:100px 0 0 0; padding:20px 20px; min-height:710px;">
        <partial name="~/Views/Shared/AllNavMenu.cshtml" />
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <!-- /page -->
    <a id="to-the-top" class="fixbtt bg-hover-theme"><i class="fa fa-chevron-up"></i></a>

    <footer class="footer-home-1 dark">

        <div class="footer-inner">
            <div class="row">
                <div class="col-md-6">
                    <a href="index.html" class="logo">
                        <img src="~/images/logo-on-dark.png" class="img-responsive" alt="Image">
                    </a>
                    <ul class="footer-link-2">
                        <li><a href="http://adm.nauka20-35.ru/">Для администратора</a></li>
                    </ul>
                </div>

                <div class="col-md-3">
                    <ul class="widget-social-list">
                        @*<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>*@
                    </ul>
                </div>
                <div class="col-md-3">
                    <div class="copyright">Copyright © 2015<br> ДТИПБ</div>
                </div>
            </div>
        </div>
    </footer>

    <!-- /Footer home 1 -->
    <!-- SCRIPT -->
    <script src="~/js/vendor/jquery.min.js"></script>
    <script src="~/js/vendor/bootstrap.js"></script>
    <script src="~/js/plugins/jquery.sticky-kit.min.js"></script>
    <script src="~/js/plugins/jquery.waypoints.min.js"></script>

    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <!-- Mobile Menu
        ================================================== -->
    <script type="text/javascript" src="~/js/plugins/jquery.mmenu.all.min.js"></script>
    <script type="text/javascript" src="~/js/plugins/mobilemenu.js"></script>
    <!-- REVOLUTION JS FILES -->
    <script type="text/javascript" src="~/revolution/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/jquery.themepunch.revolution.min.js"></script>
    <!-- SLIDER REVOLUTION 5.0 EXTENSIONS  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.actions.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.migration.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <script src="~/js/plugins/slider-home-2.js"></script>
    <!-- Initializing Owl Carousel
        ================================================== -->
    <script src="~/js/plugins/owl.carousel.js"></script>
    <script src="~/js/plugins/owl.js"></script>
    <!-- PreLoad
        ================================================== -->
    <script type="text/javascript" src="~/js/plugins/royal_preloader.js"></script>


    <!-- Global Js
        ================================================== -->
    <script src="~/js/plugins/template.js"></script>
    @* @RenderSection("Scripts", required: false)*@
</body>
</html>